# Generated by Django 3.1.7 on 2021-03-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210323_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='time',
        ),
        migrations.AddField(
            model_name='status',
            name='status_val',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
