# Generated by Django 3.1.7 on 2021-03-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='status',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
