# Generated by Django 3.1.7 on 2021-04-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210325_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed',
            field=models.BooleanField(default=False),
        ),
    ]
