# Generated by Django 3.1.7 on 2021-05-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210526_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='loading',
            field=models.BooleanField(default=False),
        ),
    ]
